version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: factorial_shop
      POSTGRES_DB: factorial_shop_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U factorial_shop"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://factorial_shop:password@db/factorial_shop_development
      RAILS_ENV: development
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  bundle_cache:
